Add NOAWT="true" workaround on Mac OS X to fix Snowball and RWeka
This prevents getting this error when running SnowballStemmer():

Error in .jnew(name) :
  java.lang.InternalError: Can't start the AWT because Java was
  started on the first thread.  Make sure StartOnFirstThread is
  not specified in your application's Info.plist or on the command line

This should get rid of the requirement to run Rcmdr from JGR on Mac OS.


git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rcmdr-tms@52 edb9625f-4e0d-4859-8d74-9fd3b1da38cb